receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      filesystem: {}
      load: {}
      network: {}
      process: {}
    host_path_prefix: "/host"


exporters:
  prometheus:
    endpoint: "0.0.0.0:${OTEL_COLLECTOR_PORT_PROM}"
  otlphttp/loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    headers:
     Content-Type: application/json


#  loki:
#    endpoint: "http://loki:3100/loki/api/v1/push"
#  headers:
#    Content-Type: application/json
#    tls:
#      insecure: true
  debug:
    verbosity: detailed


processors:
  resourcedetection:
    detectors: [env, docker, system]



service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resourcedetection]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]
