global:
  scrape_interval: 60s

#otlp:
#  keep_identifying_resource_attributes: true
#  promote_resource_attributes:
#    - service.instance.id
#    - service.name
#    - service.namespace
#    - service.version
#    - cloud.availability_zone
#    - cloud.region
#    - deployment.environment.name

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: host
        replacement: '$1'


  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']



  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

