spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
#            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
#            user-name-attribute: sub
  # GraphQL
  graphql:
    graphiql:
      enabled: true    # Enables /graphiql UI in dev
    schema:
      printer:
        enabled: true  # Allows introspection

# Zipp-specific config
zipp:
  security:
    # Allow /graphql without API key in dev
    graphql-open: true

report:
  expiration-hours: 12
